/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calUI;

/**
 *
 * @author User
 */
public class calUI extends javax.swing.JFrame {

    /**
     * Creates new form calUI
     */
    double numEnter1;
    double numEnter2;
    double result;
    String operator;
    private boolean operatorSet = false;
    boolean resultDisplayed = false;
    boolean operatorDisplayed = false;
    public calUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResults = new javax.swing.JTextField();
        btnClearScreen = new javax.swing.JButton();
        btnBackSpace = new javax.swing.JButton();
        btnPositiveOrNegative = new javax.swing.JButton();
        btndigit7 = new javax.swing.JButton();
        btndigit8 = new javax.swing.JButton();
        btndigit9 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btndigit5 = new javax.swing.JButton();
        btndigit4 = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();
        btndigit6 = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnDigit0 = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        btnMultiplication = new javax.swing.JButton();
        btnDigit3 = new javax.swing.JButton();
        btnDigit2 = new javax.swing.JButton();
        btndigit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(423, 390));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResults.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResults.setText("0");
        txtResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultsActionPerformed(evt);
            }
        });
        getContentPane().add(txtResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 370, 60));

        btnClearScreen.setText("Clear");
        btnClearScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearScreenActionPerformed(evt);
            }
        });
        getContentPane().add(btnClearScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 72, 30));

        btnBackSpace.setText("⌫");
        btnBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSpaceActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 72, 30));

        btnPositiveOrNegative.setText("±");
        btnPositiveOrNegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPositiveOrNegativeActionPerformed(evt);
            }
        });
        getContentPane().add(btnPositiveOrNegative, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 72, 30));

        btndigit7.setText("7");
        btndigit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit7ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 72, 30));

        btndigit8.setText("8");
        btndigit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit8ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 72, 30));

        btndigit9.setText("9");
        btndigit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit9ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 72, 30));

        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 72, 30));

        btndigit5.setText("5");
        btndigit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit5ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 72, 30));

        btndigit4.setText("4");
        btndigit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit4ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 72, 30));

        btnSubtract.setText("-");
        btnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 72, 30));

        btndigit6.setText("6");
        btndigit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit6ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 72, 30));

        btnDivide.setText("÷");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(btnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 72, 30));

        btnDot.setText(".");
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });
        getContentPane().add(btnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 72, 30));

        btnDigit0.setText("0");
        btnDigit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit0ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDigit0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 72, 30));

        btnEquals.setText("=");
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });
        getContentPane().add(btnEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 72, 80));

        btnMultiplication.setText("x");
        btnMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicationActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiplication, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 72, 30));

        btnDigit3.setText("3");
        btnDigit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDigit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 72, 30));

        btnDigit2.setText("2");
        btnDigit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDigit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 72, 30));

        btndigit1.setText("1");
        btndigit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit1ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 72, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void operatorSetter(){
        if (!operatorSet) {
            numEnter1 = Double.parseDouble(txtResults.getText());
            operatorSet = true;
        }
    }
    private void enterNumbers(String n){
        if (operatorSet || resultDisplayed || operatorDisplayed) {
            txtResults.setText(n);
            operatorSet = false;
            resultDisplayed = false;
            operatorDisplayed = false;
        } else {
            if (txtResults.getText().equals("0") && !n.equals("0")) {
                txtResults.setText(n);
            } else {
                txtResults.setText(txtResults.getText() + n);
        }
        }
    }
    
    private void txtResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultsActionPerformed

    private void btndigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit7ActionPerformed
        enterNumbers("7");
    }//GEN-LAST:event_btndigit7ActionPerformed

    private void btndigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit8ActionPerformed
        enterNumbers("8");
    }//GEN-LAST:event_btndigit8ActionPerformed

    private void btndigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit9ActionPerformed
        enterNumbers("9");
    }//GEN-LAST:event_btndigit9ActionPerformed

    private void btndigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit4ActionPerformed
        enterNumbers("4");
    }//GEN-LAST:event_btndigit4ActionPerformed

    private void btndigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit5ActionPerformed
        enterNumbers("5");
    }//GEN-LAST:event_btndigit5ActionPerformed

    private void btndigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit6ActionPerformed
        enterNumbers("6");
    }//GEN-LAST:event_btndigit6ActionPerformed

    private void btndigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit1ActionPerformed
        enterNumbers("1");
    }//GEN-LAST:event_btndigit1ActionPerformed

    private void btnDigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit2ActionPerformed
        enterNumbers("2");
    }//GEN-LAST:event_btnDigit2ActionPerformed

    private void btnDigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit3ActionPerformed
        enterNumbers("3");
    }//GEN-LAST:event_btnDigit3ActionPerformed

    private void btnDigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit0ActionPerformed
        enterNumbers("0");
    }//GEN-LAST:event_btnDigit0ActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        operatorSetter();
        txtResults.setText("÷");
        operator = "/";
        operatorSet = true;
        operatorDisplayed = true;
        resultDisplayed = false;
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicationActionPerformed
        operatorSetter();
        txtResults.setText("x");
        operator = "*";
        operatorSet = true;
        operatorDisplayed = true;
        resultDisplayed = false;
    }//GEN-LAST:event_btnMultiplicationActionPerformed

    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
        operatorSetter();
        txtResults.setText("-");
        operator = "-";
        operatorSet = true;
        operatorDisplayed = true;
        resultDisplayed = false;
    }//GEN-LAST:event_btnSubtractActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        operatorSetter();
        txtResults.setText("+");
        operator = "+";
        operatorSet = true;
        operatorDisplayed = true;
        resultDisplayed = false;
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearScreenActionPerformed
        txtResults.setText("0");
        numEnter1 = 0;
        numEnter2 = 0;
        operator = "";
        operatorSet = false;
    }//GEN-LAST:event_btnClearScreenActionPerformed

    private void btnPositiveOrNegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPositiveOrNegativeActionPerformed
        double number = Double.parseDouble(String.valueOf(txtResults.getText()));
        number = number * (-1);
        txtResults.setText(String.valueOf(number));
    }//GEN-LAST:event_btnPositiveOrNegativeActionPerformed

    private void btnBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSpaceActionPerformed
        if (txtResults.getText().length()>0){
            StringBuilder sb = new StringBuilder(txtResults.getText());
            sb.deleteCharAt(txtResults.getText().length() - 1);
            txtResults.setText(sb.toString());
        }
    }//GEN-LAST:event_btnBackSpaceActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        if(!txtResults.getText().contains(".")){
            txtResults.setText(txtResults.getText()+ btnDot.getText());
        }
    }//GEN-LAST:event_btnDotActionPerformed

    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
        numEnter2 = Double.parseDouble(txtResults.getText());
        if (operator == null || operator.isEmpty()) {
            txtResults.setText("0");
            return;
        }
        if(operator.equals("+")){
            result = numEnter1 + numEnter2;
        }else if(operator.equals("-")){
            result = numEnter1 - numEnter2;
        }else if(operator.equals("*")){
            result = numEnter1 * numEnter2;
        }else if(operator.equals("/")){
            if(numEnter2 == 0 ){
                txtResults.setText("ERROR");
                return;
            }else{
                result = numEnter1 / numEnter2;
            }
        }
        txtResults.setText(String.valueOf(result));
        resultDisplayed = true;
        operator = "";
        operatorSet = false;
        operatorDisplayed = false;
    }//GEN-LAST:event_btnEqualsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBackSpace;
    private javax.swing.JButton btnClearScreen;
    private javax.swing.JButton btnDigit0;
    private javax.swing.JButton btnDigit2;
    private javax.swing.JButton btnDigit3;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnMultiplication;
    private javax.swing.JButton btnPositiveOrNegative;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JButton btndigit1;
    private javax.swing.JButton btndigit4;
    private javax.swing.JButton btndigit5;
    private javax.swing.JButton btndigit6;
    private javax.swing.JButton btndigit7;
    private javax.swing.JButton btndigit8;
    private javax.swing.JButton btndigit9;
    private javax.swing.JTextField txtResults;
    // End of variables declaration//GEN-END:variables
}
